version: '3.9'

services:
  app:
    image: jeancigoli/blog-api
    restart: always
    env_file:
      - .env
    ports:
      - 80:${PORT}

  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
